services:
  - type: web
    name: paradetect-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app1:app --workers 1 --threads 1 --timeout 120

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
